<?php

/*
 * This file contains useful constants for use throughout the scripts.
 */

/** TABLE CONSTANTS. **/ 
define("TABLE_USERS", "users");
define("TABLE_GROUPS", "groups");
define("TABLE_CHILDREN", "profiles");
define("TABLE_CBMESSAGES","cbMessages");
define("TABLE_APP_SETTINGS", "appSetings");
define("TABLE_CHILD_GROUP", "childGroupKey");
define("TABLE_IMAGE_RESOURCES", "imageResources");
define("TABLE_USER_GROUP_KEYS", "userGroupKeys");
define("TABLE_NEWSPOSTS", "newsPosts");

/** SETTINGS CONSTANTS. **/
define("SETTING_LOCAL_IMAGE_PATH", "local_image_path");

?>
