<?php

/*
 * This file contains useful constants for use throughout the scripts.
 */

/** TABLE CONSTANTS. **/ 
define("TABLE_USERS", "users");
define("TABLE_GROUPS", "groups");
define("TABLE_CHILDREN", "profiles");
define("TABLE_ABILITY_DEFINITIONS", "abilityDefinitions");
define("TABLE_CBMESSAGES","cbMessages");
define("TABLE_APP_SETTINGS", "appSetings");
define("TABLE_CHILD_GROUP_KEYS", "childGroupKey");
define("TABLE_IMAGE_RESOURCES", "imageResources");
define("TABLE_USER_GROUP_KEYS", "userGroupKeys");
define("TABLE_NEWSPOSTS", "newsPosts");
define("TABLE_DEVICE_APPS", "devAppKeys");
define("TABLE_PROFILE_ABILITIES", "profileAbilities"); 
define("TABLE_KIDSPROFILE_ABILITIES", "kidsProfile_abilities");
define("TABLE_APPS" , "applications");
define("TABLE_DEVICE", "devices");
define("TABLE_CHILD_USER", "childUserKeys");
define("TABLE_IMAGE_URIS", "imageResources");

/** SETTINGS CONSTANTS. **/
define("SETTING_LOCAL_IMAGE_PATH", "local_image_path");

?>
